spring.application.name=gym-springboot

spring.profiles.default=local

logging.level.com.berruhanedar.app.gym_springboot=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger{36} - %msg%n

spring.web.locale=en
spring.web.locale-resolver=fixed

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.access=unrestricted
management.endpoint.health.access=unrestricted

management.info.env.enabled=true
info.app.name=Gym Spring Boot
info.app.description=Gym CRM REST API
info.app.version=0.0.1-SNAPSHOT

management.endpoint.health.group.readiness.include=ping,gymDatabase,gymData
management.endpoint.health.group.liveness.include=ping
