spring.application.name=gym-springboot

spring.profiles.default=local

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Circuit Breaker
resilience4j.circuitbreaker.instances.trainerWorkloadService.sliding-window-size=5
resilience4j.circuitbreaker.instances.trainerWorkloadService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.trainerWorkloadService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.trainerWorkloadService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.trainerWorkloadService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.trainerWorkloadService.automatic-transition-from-open-to-half-open-enabled=true

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger{36} - %msg%n

spring.web.locale=en
spring.web.locale-resolver=fixed

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

management.info.env.enabled=true
info.app.name=Gym Spring Boot
info.app.description=Gym CRM REST API
info.app.version=0.0.1-SNAPSHOT

management.endpoint.health.group.readiness.include=ping,gymDatabase,gymData
management.endpoint.health.group.liveness.include=ping