INSERT INTO training_types (training_type_name) VALUES ('Fitness');
INSERT INTO training_types (training_type_name) VALUES ('Yoga');
INSERT INTO training_types (training_type_name) VALUES ('Pilates');
INSERT INTO training_types (training_type_name) VALUES ('CrossFit');
INSERT INTO training_types (training_type_name) VALUES ('Strength Training');
INSERT INTO training_types (training_type_name) VALUES ('Cardio');
INSERT INTO training_types (training_type_name) VALUES ('HIIT');
INSERT INTO training_types (training_type_name) VALUES ('Zumba');
INSERT INTO training_types (training_type_name) VALUES ('Spinning');
INSERT INTO training_types (training_type_name) VALUES ('Boxing');
INSERT INTO training_types (training_type_name) VALUES ('Kickboxing');
INSERT INTO training_types (training_type_name) VALUES ('Swimming');
INSERT INTO training_types (training_type_name) VALUES ('Running');
INSERT INTO training_types (training_type_name) VALUES ('Cycling');
INSERT INTO training_types (training_type_name) VALUES ('Stretching');
INSERT INTO training_types (training_type_name) VALUES ('Functional Training');
INSERT INTO training_types (training_type_name) VALUES ('TRX');
INSERT INTO training_types (training_type_name) VALUES ('Bodybuilding');
INSERT INTO training_types (training_type_name) VALUES ('Dance Fitness');
INSERT INTO training_types (training_type_name) VALUES ('Aerobics');